# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50578d55dd6e8a7cece3731a248fcb38e2f306cd116df4cec21f4a456b6117072d35aee5f39a09fb2fb0533ef789601b27a1d9237c70619c20d7647db5d298d9

test:
  secret_key_base: 3ce31cf06d2fd9088f06103473ebc1843ebcc8e78e51ab418b71d5bed0b9eaf31420b17ecefe09a095a769d4b41c9f8b2da714ae252c4790a8a1d2cf0f467c43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
